#!/bin/bash
ocamllex preprocessor.mll
ocamlc -o preprocessor str.cma preprocessor.ml
ocamllex scanner.mll # create scanner.ml
ocamlyacc parser.mly # create parser.ml and parser.mli
ocamlc -c ast.ml # compile AST types
ocamlc -c stringify.ml
ocamlc -c parser.mli # compile parser types
ocamlc -c scanner.ml # compile the scanner
ocamlc -c parser.ml # compile the parser
ocamlc -c type_infer.ml # compile the type inference checker
ocamlc -c generator.ml # compile the generator
ocamlc -c finaltest.ml # compile the tester
ocamlc -c executor.ml # compile the executor
ocamlc -o tests unix.cma generator.cmo type_infer.cmo scanner.cmo parser.cmo stringify.cmo finaltest.cmo  # generate test runner
ocamlc -o exss unix.cma generator.cmo type_infer.cmo scanner.cmo parser.cmo stringify.cmo executor.cmo # generate exss 
